-- Receipt-only migration: L3 durable memory candidate integrated, NOT activated.
--
-- The Supabase GitHub integration automatically evaluates canonical migrations
-- after merge. Production activation gates are not yet satisfied, so this
-- canonical version intentionally performs no schema mutation.
--
-- Reviewed candidate SQL lives at:
--   supabase/candidates/20260918234500_agent_memories_l3_contract.sql
--
-- A future activation must use a NEW migration version after the activation
-- gate is green. Do not replace this receipt with schema SQL after it has been
-- observed/applied in migration history.
--
-- No schema changes.
